"""Expose the flask-diffsynth image-edit contract and proxy it to vLLM-Omni.

Public request fields (multipart/form-data):
  image: required source image
  prompt: required edit instruction
  mask: optional mask image
  mask_mode: mask_image (latent blending) or reference (second RGB reference).
             Overrides --mask-mode; reference requires mask.
  seed: optional integer seed forwarded to the upstream engine
  lora: optional JSON object {"name": "...", "path": "...", "scale": 1.0}
        Overrides the CLI default adapter; scale=0 disables it for this request.

By default the upstream request renames ``mask`` to ``mask_image``. Reference
mode sends ordered repeated ``image`` parts: source, then RGB mask, without
``mask_image``. It does not paste known pixels back into the output. Initial
diffusion noise is generated by the upstream engine; this adapter never sends
an external target/noise image or ``reference_image``.
"""

# 当前优化记录（2026-09-09）：用户要求每步完整重算，enable_reference_kv_cache=false。
# 最终部署：下面四卡 Ulysses 配置必须覆盖 NCCL_P2P_LEVEL=PHB，不能照搬历史 PIX。
# 本机 PIX 实际走 SHM/direct/direct；PHB 走 P2P/CUMEM。用 NCCL_DEBUG=INFO 验证路径。
# 同样1536双参考图、4步、C1、预热2次后10次：平均2.870s、P50 2.874s、
# P90 2.885s、P99 2.897s，10/10成功；参考KV关闭，正常regional编译，无CUDA Graph。
# 最终路径相对上一轮PIX样图：LPIPS 0.0141、SSIM 0.9865；重复seed42像素一致。
# 以下3.716/3.533/3.445s是修正NCCL路径前的阶段结果。
# 四卡、1536 双参考图、4步、C1：Ulysses INT8 + 静态合并 LoRA 为 3.716s；
# 再开 parallel_reference_encode 为 3.533s，P90 3.566s，均预热2次后10/10成功。
# Flask 追加 --output-compression 100（PNG compress_level=0）：平均3.445s、P90 3.469s，
# 10/10成功，像素不变，PNG从5.07MB增至7.08MB；这是本机HTTP结果。
# 上游沿用下方环境变量，并设置 CUDA_VISIBLE_DEVICES=0,1,2,3、SageAttention PYTHONPATH：
#   export NCCL_P2P_LEVEL=PHB
#   vllm serve /root/workspace/models/FLUX.2-klein-4B-renshihao23385-merged --omni \
#       --host 0.0.0.0 --port 8091 --num-gpus 4 --ring-degree 1 --ulysses-degree 4 \
#       --no-diffusion-compile-dynamic --quantization fp8 \
#       --diffusion-attention-backend SAGE_ATTN --diffusion-compile-granularity regional \
#       --additional-config '{"enable_reference_kv_cache":false,"ulysses_int8_transport":true,"parallel_reference_encode":true}'
# Flask 使用同一 merged 模型路径、--steps 4、--mask-mode reference；不要再次挂相同 LoRA。
# merged 是单独派生目录，原始权重和 adapter 保留；固定 alpha=64、scale=1 后再在线 FP8。
# 切换 adapter/scale 需恢复原模型的动态 LoRA 部署，不能用请求 scale=0 撤销已合并的权重。
# Ulysses INT8 量化传输 Q/K/V 和 attention 输出；与 Ring 只量化 K/V 的误差不同。
# 并行 VAE 分配参考图到各卡后汇总 latent，仍每次请求重新编码；当前样图并非像素完全等同。
# CUDA Graph 初始错误已定位为Sage默认stream问题，独立修补后正确但无明显性能收益；
# 相关实验未采用，最终部署沿用原SageAttention安装和正常编译。
#
# 以下为历史部署（2026-09-08）：双 L40S，vLLM 0.27.0 / PyTorch 2.13.0+cu130。
# vllm-omni 使用 /root/workspace/github/vllm-omni 的本地修改版，必须包含
# Klein 参考图 KV 缓存的 Ring 适配，以及向 Transformer 传入 od_config 的修复。
# enable_reference_kv_cache 不是仅靠官方模型文件就能开启的通用参数。
#
# 先在一个终端启动 vLLM-Omni 上游（以下路径对应当前远程机器）：
#   export CUDA_VISIBLE_DEVICES=0,1
#   export NCCL_P2P_LEVEL=PIX
#   export LD_LIBRARY_PATH=/root/workspace/cuda-compat/usr/local/cuda-13.3/compat:${LD_LIBRARY_PATH:-}
#   export PATH=/root/workspace/envs/omni/bin:$PATH
#   export TORCHINDUCTOR_CACHE_DIR=/root/workspace/cache/torchinductor
#   export TRITON_CACHE_DIR=/root/workspace/cache/triton
#   export HF_HUB_OFFLINE=1
#   export HF_HUB_DISABLE_TELEMETRY=1
#   export TOKENIZERS_PARALLELISM=false
#   vllm serve /root/workspace/models/FLUX.2-klein-4B --omni \
#       --host 0.0.0.0 --port 8091 \
#       --num-gpus 2 --ring-degree 2 --no-diffusion-compile-dynamic \
#       --quantization fp8 --diffusion-compile-granularity regional \
#       --additional-config '{"enable_reference_kv_cache": true}'
#
# 再在另一个终端启动本适配器（默认不启用 CFG）：
#   /root/workspace/envs/omni/bin/python flask-vllm.py \
#       --model /root/workspace/models/FLUX.2-klein-4B --steps 4 \
#       --upstream-url http://127.0.0.1:8091/v1/images/edits \
#       --timeout 1200 --host :: --port 8512
# 若环境设置了 HTTP 代理，NO_PROXY/no_proxy 必须包含 localhost,127.0.0.1。
#
# 注意：使用 Ring=2，TP 保持默认 1；本机 TP=2 实测更慢。
# 参考 KV 仅在一次请求的去噪步骤间复用，首步提取、后续三步复用。
# 生成和参考 token 数需分别被 Ring degree 整除；暂不支持 Ulysses/AllGather-KV。
# 该选项改变普通 Klein 的参考 attention 和时间步条件，并非无损推理优化。
# 本地 pipeline 还包含 VAE encode/decode 编译和相同 prompt 的 TE 缓存。
# 1536x1536、4 步、单并发、预热 2 次后测 10 次（服务机本地 HTTP）：
#   Ring=2 + 完整参考 KV：平均 2.450s，P50 2.449s，P90 2.465s，10/10 成功。
#   每层首步 AllGather 完整参考 K/V，后续 Ring 只传生成 KV；参考 KV 本地复用。
#   单流层必须向 attention 传递 text_seq_len，确保文本 KV 只参与一次。
#   旧版分片 KV 为 2.913s，但也缺少上述文本长度传递修复，不能仅归因于通信。
#   此前单卡 + KV：3.376s；TP=2 + KV：5.287s。首次编译不计入稳态延迟。
#
# 关闭参考 KV 的低精度加速路径（同机 1536x1536 / 4 步 / C1）：
#   export PYTHONPATH=/root/workspace/sageattention2:${PYTHONPATH:-}
#   上述上游命令增加 --diffusion-attention-backend SAGE_ATTN，并替换为：
#   --additional-config '{"enable_reference_kv_cache": false, "ring_int8_transport": true}'
#   需要额外安装 SageAttention 2.2.0（本机编译自 d1a57a546c3d395b1ffcbeecc66d81db76f3b4b5）。
#   仍使用完整 attention，每层每步重算 K/V；INT8 仅压缩跨卡传输，不跨步缓存。
#   注意这是近似优化：Sage 的 QK/PV 和 Ring 传输都会引入量化误差，默认不开启。
#   预热 2 次后测 10 次：FA3/BF16 3.354s；Sage/BF16 3.201s；Sage/INT8 2.945s。
#   Sage/INT8 的 P90 为 2.972s，10/10 成功。移除两个新增选项即可恢复原精度。
#   最终代码重启后复测 20 次：平均 2.951s，P50 2.952s，P90 2.970s，20/20 成功。
#
# LoRA 已验证（2026-09-09）：renshihao.01-step-23385，双卡 Ring=2，以上量化全开。
# 原文件来自 HDFS 的 FLUX.2-klein-4B/lora 目录；转换副本为 PEFT 目录：
#   /root/workspace/models/FLUX.2-klein-4B/lora/renshihao-23385-peft
# 转换仅去掉权重名中的 .default；原文件保留。rank=64，因没有 alpha 元数据，
# 按 alpha=64、scale=1.0 验证；若训练使用不同 alpha，需要调整 adapter_config.json。
# 上游命令追加 --lora-path <PEFT目录> --lora-scale 1.0，在编译前安装 LoRA 层。
# 本 Flask 命令也追加 --lora-path <PEFT目录> --lora-name renshihao --lora-scale 1.0。
# Flask 必须每次显式传 LoRA，上游 PEFT 在没有 lora_request 时会停用 adapter。
# 不配置 --lora-path 时保持原先无 LoRA 请求行为；请求级 lora JSON 可覆盖默认值。
# 双参考图扩图：Flask 追加 --mask-mode reference，或请求传 mask_mode=reference。
# 上游 model_metadata.py 必须为 Flux2KleinPipeline 声明 supports_multimodal_inputs=True、
# max_multimodal_image_inputs=2，否则 API 会在进入 pipeline 前拒绝双图。
# 上传 image + mask，蒙版转换为 RGB PNG 后作为第二张 image，原图为第一张。
# 默认 mask_image 保留原来的 latent 蒙版混合；两种模式均不做最终像素贴回。
# 四卡 INT8 Ring 已验证（2026-09-09）：CUDA_VISIBLE_DEVICES=0,1,2,3，
# 上游 --num-gpus 4 --ring-degree 4，保留 FP8/SAGE_ATTN/ring_int8_transport=true。
# 需要支持多跳原始 INT8 包转发的 ring_flash_attn.py（旧实现仅支持两卡）。
# 1536 双参考图、LoRA、4步、KV关闭、C1，预热2次后10次平均4.624s，P90 4.656s。
# 同输入四卡 BF16 通信6.212s，双卡INT8通信5.392s；均为本机HTTP端到端耗时。

import argparse
import io
import json
import logging
import math
import typing as ty
from dataclasses import dataclass

import requests
from flask import Flask, Response, jsonify, request
from PIL import Image


@dataclass(frozen=True)
class ServerConfig:
    upstream_url: str
    model: str
    steps: int
    enable_cfg: bool
    guidance_scale: float
    output_compression: int
    timeout: float
    host: str
    port: int
    lora_path: str | None = None
    lora_name: str = "default"
    lora_scale: float = 1.0
    mask_mode: str = "mask_image"


class VllmImageEditAdapter:
    def __init__(self, config: ServerConfig) -> None:
        self.config = config
        self.session = requests.Session()
        self.app = Flask(__name__)
        self.app.post("/v1/images/edits")(self.edit_image)
        self.app.get("/health")(self.health)

    @staticmethod
    def error(message: str, status: int) -> tuple[Response, int]:
        return (
            jsonify(
                {
                    "error": {
                        "message": message,
                        "type": "invalid_request_error"
                        if status < 500
                        else "upstream_error",
                    }
                }
            ),
            status,
        )

    @staticmethod
    def read_upload(name: str, required: bool) -> tuple[bytes, str, str] | None:
        upload = request.files.get(name)
        if upload is None:
            if required:
                raise ValueError(f"missing {name}")
            return None
        data = upload.stream.read()
        if not data:
            raise ValueError(f"empty {name}")
        return data, upload.filename or f"{name}.png", upload.mimetype or "image/png"

    @staticmethod
    def image_size(data: bytes, name: str) -> tuple[int, int]:
        try:
            with Image.open(io.BytesIO(data)) as image:
                # Dimensions live in the image header. Decoding every source
                # and mask here duplicates the upstream decoder and adds
                # avoidable latency to this pass-through adapter.
                return image.size
        except Exception as exc:
            raise ValueError(f"invalid {name}: {exc}") from exc

    def health(self) -> Response | tuple[Response, int]:
        health_url = self.config.upstream_url.rsplit("/v1/images/edits", 1)[0] + "/health"
        try:
            upstream = self.session.get(health_url, timeout=min(self.config.timeout, 5.0))
        except requests.RequestException as exc:
            return self.error(f"vLLM health check failed: {exc}", 503)
        if upstream.status_code != 200:
            return self.error(
                f"vLLM health check returned HTTP {upstream.status_code}", 503
            )
        return jsonify({"status": "ok", "upstream": health_url})

    @staticmethod
    def reference_mask(data: bytes) -> bytes:
        """Match the conditioning script's L -> RGB conversion, losslessly."""
        try:
            with Image.open(io.BytesIO(data)) as mask:
                buffer = io.BytesIO()
                mask.convert("L").convert("RGB").save(buffer, format="PNG")
                return buffer.getvalue()
        except Exception as exc:
            raise ValueError(f"invalid mask: {exc}") from exc

    def edit_image(self) -> Response | tuple[Response, int]:
        try:
            image_upload = ty.cast(
                tuple[bytes, str, str], self.read_upload("image", required=True)
            )
            mask_upload = self.read_upload("mask", required=False)
            mask_mode = request.form.get("mask_mode", self.config.mask_mode)
            if mask_mode not in ("mask_image", "reference"):
                raise ValueError("mask_mode must be mask_image or reference")
            if mask_mode == "reference" and mask_upload is None:
                raise ValueError("mask is required when mask_mode=reference")
            prompt = request.form.get("prompt", "")
            if not prompt:
                raise ValueError("missing prompt")
            width, height = self.image_size(image_upload[0], "image")
            if mask_upload is not None:
                mask_size = self.image_size(mask_upload[0], "mask")
                if mask_size != (width, height):
                    raise ValueError(
                        f"mask size {mask_size[0]}x{mask_size[1]} must match image size "
                        f"{width}x{height}"
                    )
                if mask_mode == "reference":
                    mask_upload = (self.reference_mask(mask_upload[0]), "mask-reference.png", "image/png")
        except ValueError as exc:
            return self.error(str(exc), 400)

        files: list[tuple[str, tuple[str, bytes, str]]] = [
            ("image", (image_upload[1], image_upload[0], image_upload[2]))
        ]
        if mask_upload is not None:
            files.append((
                "image" if mask_mode == "reference" else "mask_image",
                (mask_upload[1], mask_upload[0], mask_upload[2]),
            ))

        fields: dict[str, str] = {
            "model": self.config.model,
            "prompt": prompt,
            "size": f"{width}x{height}",
            "num_inference_steps": str(self.config.steps),
            "response_format": "b64_json",
            # vLLM maps 88 to PNG compress_level=1, matching flask-diffsynth.
            # Its default of 100 maps to level 0 and produces responses that
            # are several times larger, adding avoidable Base64/HTTP overhead.
            "output_compression": str(self.config.output_compression),
        }
        if self.config.enable_cfg:
            fields["guidance_scale"] = str(self.config.guidance_scale)
            fields["true_cfg_scale"] = str(self.config.guidance_scale)
        else:
            fields["guidance_scale"] = "0"
            fields["true_cfg_scale"] = "0"

        try:
            lora = None
            if self.config.lora_path:
                lora = {"name": self.config.lora_name, "path": self.config.lora_path,
                        "scale": self.config.lora_scale}
            if "lora" in request.form:
                lora = json.loads(request.form["lora"])
                if not isinstance(lora, dict):
                    raise ValueError("lora must be a JSON object")
            if lora is not None:
                if not all(isinstance(lora.get(k), str) and lora[k].strip() for k in ("name", "path")):
                    raise ValueError("lora requires nonempty name and path strings")
                scale = float(lora.get("scale", 1.0))
                if not math.isfinite(scale):
                    raise ValueError("lora scale must be finite")
                fields["lora"] = json.dumps({"name": lora["name"], "path": lora["path"], "scale": scale})
            if "seed" in request.form:
                fields["seed"] = str(int(request.form["seed"]))
        except (ValueError, TypeError) as exc:
            return self.error(str(exc), 400)

        try:
            upstream = self.session.post(
                self.config.upstream_url,
                data=fields,
                files=files,
                timeout=self.config.timeout,
            )
        except requests.Timeout:
            return self.error(
                f"vLLM request timed out after {self.config.timeout:g}s", 504
            )
        except requests.RequestException as exc:
            return self.error(f"vLLM request failed: {exc}", 502)

        response = Response(
            upstream.content,
            status=upstream.status_code,
            content_type=upstream.headers.get("content-type", "application/json"),
        )
        for header in ("x-request-id", "openai-processing-ms"):
            if header in upstream.headers:
                response.headers[header] = upstream.headers[header]
        return response

    def run(self) -> None:
        logging.info(
            "proxying %s to %s model=%s steps=%d enable_cfg=%s",
            "/v1/images/edits",
            self.config.upstream_url,
            self.config.model,
            self.config.steps,
            self.config.enable_cfg,
        )
        self.app.run(host=self.config.host, port=self.config.port, threaded=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Translate the flask-diffsynth image-edit API to vLLM-Omni."
    )
    parser.add_argument("--model", required=True, help="Model name/path sent to vLLM.")
    parser.add_argument("--steps", type=int, required=True)
    parser.add_argument("--lora-path", help="Default PEFT adapter directory on the upstream server.")
    parser.add_argument("--lora-name", default="default")
    parser.add_argument("--lora-scale", type=float, default=1.0)
    parser.add_argument("--mask-mode", choices=("mask_image", "reference"), default="mask_image",
                        help="Use mask for latent blending or as a second RGB reference image.")
    parser.add_argument("--enable-cfg", action="store_true")
    parser.add_argument("--guidance-scale", type=float)
    parser.add_argument(
        "--upstream-url",
        default="http://127.0.0.1:8091/v1/images/edits",
    )
    parser.add_argument("--timeout", type=float, default=300.0)
    parser.add_argument(
        "--output-compression",
        type=int,
        default=88,
        help="vLLM output compression (0..100); 88 maps PNG to compress_level=1.",
    )
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8512)
    return parser.parse_args()


def config_from_args(args: argparse.Namespace) -> ServerConfig:
    if args.steps <= 0:
        raise ValueError("--steps must be positive")
    if args.timeout <= 0:
        raise ValueError("--timeout must be positive")
    if not math.isfinite(args.lora_scale):
        raise ValueError("--lora-scale must be finite")
    if not 0 <= args.output_compression <= 100:
        raise ValueError("--output-compression must be between 0 and 100")
    if args.enable_cfg and args.guidance_scale is None:
        raise ValueError("--guidance-scale is required when --enable-cfg is set")
    return ServerConfig(
        upstream_url=args.upstream_url,
        model=args.model,
        steps=args.steps,
        enable_cfg=args.enable_cfg,
        guidance_scale=args.guidance_scale if args.guidance_scale is not None else 1.0,
        output_compression=args.output_compression,
        timeout=args.timeout,
        host=args.host,
        port=args.port,
        lora_path=args.lora_path,
        lora_name=args.lora_name,
        lora_scale=args.lora_scale,
        mask_mode=args.mask_mode,
    )


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s.%(msecs)03d - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    VllmImageEditAdapter(config_from_args(parse_args())).run()
