"""Expose the flask-diffsynth image-edit contract and proxy it to vLLM-Omni.

Public request fields (multipart/form-data):
  image: required source image
  prompt: required edit instruction
  mask: optional mask image

The upstream vLLM-Omni request renames ``mask`` to ``mask_image``. Initial
diffusion noise is generated by the upstream engine; this adapter never sends
an external target/noise image or ``reference_image``.
"""

import argparse
import io
import logging
import typing as ty
from dataclasses import dataclass

import requests
from flask import Flask, Response, jsonify, request
from PIL import Image


@dataclass(frozen=True)
class ServerConfig:
    upstream_url: str
    model: str
    steps: int
    enable_cfg: bool
    guidance_scale: float
    output_compression: int
    timeout: float
    host: str
    port: int


class VllmImageEditAdapter:
    def __init__(self, config: ServerConfig) -> None:
        self.config = config
        self.session = requests.Session()
        self.app = Flask(__name__)
        self.app.post("/v1/images/edits")(self.edit_image)
        self.app.get("/health")(self.health)

    @staticmethod
    def error(message: str, status: int) -> tuple[Response, int]:
        return (
            jsonify(
                {
                    "error": {
                        "message": message,
                        "type": "invalid_request_error"
                        if status < 500
                        else "upstream_error",
                    }
                }
            ),
            status,
        )

    @staticmethod
    def read_upload(name: str, required: bool) -> tuple[bytes, str, str] | None:
        upload = request.files.get(name)
        if upload is None:
            if required:
                raise ValueError(f"missing {name}")
            return None
        data = upload.stream.read()
        if not data:
            raise ValueError(f"empty {name}")
        return data, upload.filename or f"{name}.png", upload.mimetype or "image/png"

    @staticmethod
    def image_size(data: bytes, name: str) -> tuple[int, int]:
        try:
            with Image.open(io.BytesIO(data)) as image:
                # Dimensions live in the image header. Decoding every source
                # and mask here duplicates the upstream decoder and adds
                # avoidable latency to this pass-through adapter.
                return image.size
        except Exception as exc:
            raise ValueError(f"invalid {name}: {exc}") from exc

    def health(self) -> Response | tuple[Response, int]:
        health_url = self.config.upstream_url.rsplit("/v1/images/edits", 1)[0] + "/health"
        try:
            upstream = self.session.get(health_url, timeout=min(self.config.timeout, 5.0))
        except requests.RequestException as exc:
            return self.error(f"vLLM health check failed: {exc}", 503)
        if upstream.status_code != 200:
            return self.error(
                f"vLLM health check returned HTTP {upstream.status_code}", 503
            )
        return jsonify({"status": "ok", "upstream": health_url})

    def edit_image(self) -> Response | tuple[Response, int]:
        try:
            image_upload = ty.cast(
                tuple[bytes, str, str], self.read_upload("image", required=True)
            )
            mask_upload = self.read_upload("mask", required=False)
            prompt = request.form.get("prompt", "")
            if not prompt:
                raise ValueError("missing prompt")
            width, height = self.image_size(image_upload[0], "image")
            if mask_upload is not None:
                mask_size = self.image_size(mask_upload[0], "mask")
                if mask_size != (width, height):
                    raise ValueError(
                        f"mask size {mask_size[0]}x{mask_size[1]} must match image size "
                        f"{width}x{height}"
                    )
        except ValueError as exc:
            return self.error(str(exc), 400)

        files: dict[str, tuple[str, bytes, str]] = {
            "image": (image_upload[1], image_upload[0], image_upload[2])
        }
        if mask_upload is not None:
            files["mask_image"] = (
                mask_upload[1],
                mask_upload[0],
                mask_upload[2],
            )

        fields: dict[str, str] = {
            "model": self.config.model,
            "prompt": prompt,
            "size": f"{width}x{height}",
            "num_inference_steps": str(self.config.steps),
            "response_format": "b64_json",
            # vLLM maps 88 to PNG compress_level=1, matching flask-diffsynth.
            # Its default of 100 maps to level 0 and produces responses that
            # are several times larger, adding avoidable Base64/HTTP overhead.
            "output_compression": str(self.config.output_compression),
        }
        if self.config.enable_cfg:
            fields["guidance_scale"] = str(self.config.guidance_scale)
            fields["true_cfg_scale"] = str(self.config.guidance_scale)
        else:
            fields["guidance_scale"] = "0"
            fields["true_cfg_scale"] = "0"

        try:
            upstream = self.session.post(
                self.config.upstream_url,
                data=fields,
                files=files,
                timeout=self.config.timeout,
            )
        except requests.Timeout:
            return self.error(
                f"vLLM request timed out after {self.config.timeout:g}s", 504
            )
        except requests.RequestException as exc:
            return self.error(f"vLLM request failed: {exc}", 502)

        response = Response(
            upstream.content,
            status=upstream.status_code,
            content_type=upstream.headers.get("content-type", "application/json"),
        )
        for header in ("x-request-id", "openai-processing-ms"):
            if header in upstream.headers:
                response.headers[header] = upstream.headers[header]
        return response

    def run(self) -> None:
        logging.info(
            "proxying %s to %s model=%s steps=%d enable_cfg=%s",
            "/v1/images/edits",
            self.config.upstream_url,
            self.config.model,
            self.config.steps,
            self.config.enable_cfg,
        )
        self.app.run(host=self.config.host, port=self.config.port, threaded=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Translate the flask-diffsynth image-edit API to vLLM-Omni."
    )
    parser.add_argument("--model", required=True, help="Model name/path sent to vLLM.")
    parser.add_argument("--steps", type=int, required=True)
    parser.add_argument("--enable-cfg", action="store_true")
    parser.add_argument("--guidance-scale", type=float)
    parser.add_argument(
        "--upstream-url",
        default="http://127.0.0.1:8091/v1/images/edits",
    )
    parser.add_argument("--timeout", type=float, default=300.0)
    parser.add_argument(
        "--output-compression",
        type=int,
        default=88,
        help="vLLM output compression (0..100); 88 maps PNG to compress_level=1.",
    )
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8512)
    return parser.parse_args()


def config_from_args(args: argparse.Namespace) -> ServerConfig:
    if args.steps <= 0:
        raise ValueError("--steps must be positive")
    if args.timeout <= 0:
        raise ValueError("--timeout must be positive")
    if not 0 <= args.output_compression <= 100:
        raise ValueError("--output-compression must be between 0 and 100")
    if args.enable_cfg and args.guidance_scale is None:
        raise ValueError("--guidance-scale is required when --enable-cfg is set")
    return ServerConfig(
        upstream_url=args.upstream_url,
        model=args.model,
        steps=args.steps,
        enable_cfg=args.enable_cfg,
        guidance_scale=args.guidance_scale if args.guidance_scale is not None else 1.0,
        output_compression=args.output_compression,
        timeout=args.timeout,
        host=args.host,
        port=args.port,
    )


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s.%(msecs)03d - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    VllmImageEditAdapter(config_from_args(parse_args())).run()
