function(get_relative_path result base_path target_path)
    get_filename_component(base_path_abs "${base_path}" ABSOLUTE)
    get_filename_component(target_path_abs "${target_path}" ABSOLUTE)
    string(FIND "${target_path_abs}" "${base_path_abs}" common_prefix_pos)

    if (common_prefix_pos EQUAL 0)
        string(LENGTH "${base_path_abs}" base_path_length)
        math(EXPR relative_path_start "${base_path_length} + 1")
        string(SUBSTRING "${target_path_abs}" "${relative_path_start}" -1 relative_path)
    else()
        set(relative_path "")
        set(base_path_remaining "${base_path_abs}")
        while (NOT "${target_path_abs}" MATCHES "^${base_path_remaining}")
            get_filename_component(base_path_remaining "${base_path_remaining}" PATH)
            set(relative_path "../${relative_path}")
        endwhile()
        string(LENGTH "${base_path_remaining}" base_path_remaining_length)
        math(EXPR relative_path_start "${base_path_remaining_length} + 1")
        string(SUBSTRING "${target_path_abs}" "${relative_path_start}" -1 target_path_remaining)
        set(relative_path "${relative_path}${target_path_remaining}")
    endif()

    set(${result} "${relative_path}" PARENT_SCOPE)
endfunction()