FROM mirrors.tencent.com/tlinux/tlinux4.0 AS builder_stage_0

RUN yum update -y \
    && yum install wget bzip2 gcc make which gmp-devel mpfr-devel libmpc-devel texinfo -y \
    && yum groupinstall "Development Tools" -y \
    && yum-builddep python3 -y \
    && yum install git-lfs -y

RUN mkdir /.docker_workspace

ENV _docker_cmake_version="3.26.3"
FROM builder_stage_0 AS cmake_builder
RUN cd /.docker_workspace \
    && wget https://github.com/Kitware/CMake/releases/download/v${_docker_cmake_version}/cmake-${_docker_cmake_version}-linux-x86_64.sh \
    && chmod +x cmake-${_docker_cmake_version}-linux-x86_64.sh && echo "y\ny\n" | ./cmake-${_docker_cmake_version}-linux-x86_64.sh \
    && ln -s /.docker_workspace/cmake-${_docker_cmake_version}-linux-x86_64/bin/* /usr/local/bin

FROM builder_stage_0 AS builder_stage_1
COPY --from=cmake_builder /.docker_workspace/cmake-${_docker_cmake_version}-linux-x86_64 /usr/local/cmake-${_docker_cmake_version}

ENV CC=/usr/bin/gcc 
ENV CXX=/usr/bin/g++
ENV PATH=/usr/local/cmake-${_docker_cmake_version}/bin:$PATH

ENV _docker_cpython_version="3.10.15"
FROM builder_stage_1 AS cpython_builder
RUN cd /.docker_workspace &&\
    wget https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1w.tar.gz &&\
    tar -xvf OpenSSL_1_1_1w.tar.gz &&\
    cd openssl-OpenSSL_1_1_1w &&\
    mkdir build &&\
    cd build &&\
    ../config --prefix=/usr/local/openssl-1.1.1w &&\
    make -j &&\
    make install
RUN cd /.docker_workspace &&\
    wget https://github.com/python/cpython/archive/refs/tags/v${_docker_cpython_version}.zip &&\
    unzip v${_docker_cpython_version}.zip && cd cpython-${_docker_cpython_version} &&\
    ./configure --prefix=/usr/local/cpython-${_docker_cpython_version} --enable-optimizations --with-openssl=/usr/local/openssl-1.1.1w --with-openssl-rpath=auto &&\
    make -j && make install
RUN cd /usr/local/cpython-${_docker_cpython_version} && ln -s lib lib64 && cd bin && ln -s python3 python
ENV PATH=/usr/local/cpython-${_docker_cpython_version}/bin:$PATH
RUN python -m pip install --upgrade pip
RUN python -m pip install build twine wheel
RUN python -m pip install vllm

ENV _docker_ctk_version="12.8"
FROM builder_stage_1 AS ctk_builder
WORKDIR /.docker_workspace
RUN wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda_12.8.0_570.86.10_linux.run
RUN chmod +x cuda_12.8.0_570.86.10_linux.run && ./cuda_12.8.0_570.86.10_linux.run --silent --toolkit

FROM builder_stage_1 AS builder_stage_2
COPY --from=cpython_builder /usr/local/openssl-1.1.1w /usr/local/openssl-1.1.1w
COPY --from=cpython_builder /usr/local/cpython-${_docker_cpython_version} /usr/local/cpython-${_docker_cpython_version}
COPY --from=ctk_builder /usr/local/cuda-12.8 /usr/local/cuda-12.8
RUN ln -s /usr/local/cuda-12.8 /usr/local/cuda

RUN yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
RUN yum install libnccl-2.20.5-1+cuda12.2 libnccl-devel-2.20.5-1+cuda12.2 libnccl-static-2.20.5-1+cuda12.2 -y

# openmpi-4.1.6
ENV _docker_openmpi_version="4.1.6" _docker_openmpi_major_version="4" _docker_openmpi_minor_version="1"
FROM builder_stage_2 AS openmpi_builder
WORKDIR /.docker_workspace
RUN wget https://download.open-mpi.org/release/open-mpi/v${_docker_openmpi_major_version}.${_docker_openmpi_minor_version}/openmpi-${_docker_openmpi_version}.tar.gz
RUN tar -xvf openmpi-${_docker_openmpi_version}.tar.gz
RUN cd openmpi-${_docker_openmpi_version} && ./configure --enable-mpi-cxx --prefix=/usr/local/openmpi-${_docker_openmpi_version}
RUN cd openmpi-${_docker_openmpi_version} && make -j && make install

FROM builder_stage_2 AS S3
COPY --from=openmpi_builder /usr/local/openmpi-${_docker_openmpi_version} /usr/local/openmpi-${_docker_openmpi_version}
RUN ln -s /usr/local/openmpi-${_docker_openmpi_version} /usr/local/openmpi

ENV PATH=/usr/local/cpython-${_docker_cpython_version}/bin:/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
